-- 11. Our error rate must be a measurement, not arithmetic on the seed's own constants.
--
-- Until now `our_error_rate` counted every audit row, and 2,800 of those rows are background
-- corpus: their verdict was written by `supabase/seed/run.ts` and the citizen's yes/no beside
-- it was a `chance()` roll the same script made. Comparing the two and publishing the
-- difference as "how often we are wrong" measured nothing except two constants a developer
-- chose. On a site whose whole claim is measurement integrity that was the worst sentence in
-- the repository.
--
-- So: `our_error_rate` now counts only rows a real model produced (`model <> 'seed'`). The n
-- is small and honest, and the page says so. The seeded figures keep existing — they are
-- useful as a shape — but under a name no reader can mistake for a measurement.
--
-- Note on `transferred_lawfully` (migration 10): it is deliberately absent from the
-- negative-verdict list below. A mandated transfer to a competent authority is correct
-- procedure, so a department that does it and is later told the problem was fixed has not
-- been treated harshly by us. Adding it here would manufacture our own error rate.

create or replace view our_error_rate as
select
  count(*) filter (where a.verdict = 'resolved' and c.resolved = false)          as too_soft,
  count(*) filter (where a.verdict in ('deflected','boilerplate','non_responsive')
                     and c.resolved = true)                                      as too_harsh,
  count(*)                                                                       as total_compared
from audits a
join confirmations c on c.grievance_id = a.grievance_id and c.supersedes_id is null
where a.model <> 'seed';

-- The seeded corpus, under a name that cannot be read as a measurement. Same arithmetic as
-- above, over rows whose verdicts and citizen answers were both generated by the seed. Shown
-- only under the "What we simulated" heading on /numbers.
create or replace view simulated_corpus_rate as
select
  count(*) filter (where a.verdict = 'resolved' and c.resolved = false)          as too_soft,
  count(*) filter (where a.verdict in ('deflected','boilerplate','non_responsive')
                     and c.resolved = true)                                      as too_harsh,
  count(*)                                                                       as total_compared
from audits a
join confirmations c on c.grievance_id = a.grievance_id and c.supersedes_id is null
where a.model = 'seed';
