-- 12. The next step: what the citizen should actually do, per case.
--
-- A domain review found that the one action this product offered — a CPGRAMS appeal — is the
-- wrong forum for all three demo cases. Diagnosing a closure and then pointing at a door that
-- does not open is worse than saying nothing, because the citizen spends weeks on it.
--
-- So the correct forum is DATA, carried on the case, written by a human who knows the ladder,
-- and never generated by a model. Two nullable columns rather than a table: there is exactly
-- one next step per case and no history requirement. Where they are null the page renders
-- nothing at all — a generic invention would be the same harm in a new coat.

alter table grievances add column if not exists next_step_heading text;
alter table grievances add column if not exists next_step_body    text;

comment on column grievances.next_step_body is
  'Hand-written, in the citizen''s own language. Never model-generated, never a legal opinion, and never names an individual official.';
